<template>
	<div class="bg-gray-900 text-visudo-green">
		<div class="w-3/4 mx-auto text-2xl font-black text-center pt-8">Follow-Bot Privacy Policy</div>
		<div class="text-center mb-4">Last updated: December 10, 2021</div>
		<div class="w-3/4 mx-auto text-left mb-4">This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</div>
		<div class="w-3/4 mx-auto text-left mb-4">We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the <a href="https://www.privacypolicies.com/privacy-policy-generator/" target="_blank" class="text-visudo-blue hover:text-blue-300">Privacy Policy Generator</a>.</div>
		<div class="w-1/2 text-2xl mx-auto text-center mb-4">Interpretation and Definitions</div>
		<div class="w-1/2 text-2xl mx-auto text-center mb-2">Interpretation</div>
		<div class="w-3/4 mx-auto text-left mb-4">The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</div>
		<div class="w-1/2 text-2xl mx-auto text-center mb-4">Definitions</div>
		<div class="w-1/2 text-lg mx-auto text-center mb-4 font-black">For the purposes of this Privacy Policy:</div>
		<div class="w-3/4 mx-auto text-left mb-4"><strong class="text-visudo-blue">Account</strong> means a unique account created for You to access our Service or parts of our Service.</div>
		<div class="w-3/4 mx-auto text-left mb-4"><strong class="text-visudo-blue">Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</div>
		<div class="w-3/4 mx-auto text-left mb-4"><strong class="text-visudo-blue">Application</strong> means the software program provided by the Company downloaded by You on any electronic device, named Follow-Bot</div>
		<div class="w-3/4 mx-auto text-left mb-4"><strong class="text-visudo-blue">Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Follow-Bot.</div>
		<div class="w-3/4 mx-auto text-left mb-4"><strong class="text-visudo-blue">Country</strong> refers to: Ohio,  United States</div>
		<div class="w-3/4 mx-auto text-left mb-4"><strong class="text-visudo-blue">Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</div>
		<div class="w-3/4 mx-auto text-left mb-4"><strong class="text-visudo-blue">Personal Data</strong> is any information that relates to an identified or identifiable individual.</div>
		<div class="w-3/4 mx-auto text-left mb-4"><strong class="text-visudo-blue">Service</strong> refers to the Application.</div>
		<div class="w-3/4 mx-auto text-left mb-4"><strong class="text-visudo-blue">Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</div>
		<div class="w-3/4 mx-auto text-left mb-4"><strong class="text-visudo-blue">Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service.</div>
		<div class="w-3/4 mx-auto text-left mb-4"><strong class="text-visudo-blue">Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</div>
		<div class="w-3/4 mx-auto text-left mb-4"><strong class="text-visudo-blue">You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</div>
		<div class="w-1/2 text-2xl mx-auto text-center mb-4">Collecting and Using Your Personal Data</div>
		<div class="w-1/2 text-xl mx-auto text-center mb-4">Types of Data Collected</div>
		<div class="w-1/2 text-lg mx-auto text-center mb-4 font-bold">Personal Data</div>
		<div class="w-3/4 mx-auto text-left mb-4">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to: your Discord Account name, your Discord Account ID (unique to you), the Discord Servers that you are in.</div>
		<div class="w-1/2 text-lg mx-auto text-center mb-4 font-bold">Information from Third-Party Social Media Services</div>
		<div class="w-3/4 mx-auto text-left mb-4">The Company allows You to use the Service through the following Third-party Social Media Services:</div>
		<div class="w-3/4 mx-auto text-left mb-4">Discord</div>
		<div class="w-3/4 mx-auto text-left mb-4">If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal data that is already associated with Your Third-Party Social Media Service's account, such as Your name, Your email address, Your activities or Your contact list associated with that account.</div>
		<div class="w-3/4 mx-auto text-left mb-4">You may also have the option of sharing additional information with the Company through Your Third-Party Social Media Service's account. If You choose to provide such information and Personal Data, during registration or otherwise, You are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy.</div>
		<div class="w-1/2 text-2xl mx-auto text-center mb-4">Use of Your Personal Data</div>
		<div class="w-3/4 mx-auto text-left mb-4">The Company may use Personal Data for the following purposes:</div>
		<div class="w-3/4 mx-auto text-left mb-4"><strong class="text-visudo-blue">To provide and maintain our Service</strong>, including to monitor the usage of our Service.</div>
		<div class="w-3/4 mx-auto text-left mb-4"><strong class="text-visudo-blue">To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</div>
		<div class="w-3/4 mx-auto text-left mb-4"><strong class="text-visudo-blue">For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</div>
		<div class="w-3/4 mx-auto text-left mb-4"><strong class="text-visudo-blue">To manage Your requests:</strong> To attend and manage Your requests to Us.</div>
		<div class="w-3/4 mx-auto text-left mb-4"><strong class="text-visudo-blue">For other purposes</strong>: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</div>
		<div class="w-1/2 text-2xl mx-auto text-center mb-4">Retention of Your Personal Data</div>
		<div class="w-3/4 mx-auto text-left mb-4">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</div>
		<div class="w-3/4 mx-auto text-left mb-4">The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</div>
		<div class="w-1/2 text-2xl mx-auto text-center mb-4">Disclosure of Your Personal Data</div>
		<div class="w-1/2 text-xl mx-auto text-center mb-4">Business Transactions</div>
		<div class="w-3/4 mx-auto text-left mb-4">If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</div>
		<div class="w-1/2 text-xl mx-auto text-center mb-4">Law enforcement</div>
		<div class="w-3/4 mx-auto text-left mb-4">Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</div>
		<div class="w-1/2 text-xl mx-auto text-center mb-4">Other legal requirements</div>
		<div class="w-3/4 mx-auto text-left mb-4">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</div>
		<ul>
		<li class="w-3/4 mx-auto text-left mb-4">Comply with a legal obligation</li>
		<li class="w-3/4 mx-auto text-left mb-4">Protect and defend the rights or property of the Company</li>
		<li class="w-3/4 mx-auto text-left mb-4">Prevent or investigate possible wrongdoing in connection with the Service</li>
		<li class="w-3/4 mx-auto text-left mb-4">Protect the personal safety of Users of the Service or the public</li>
		<li class="w-3/4 mx-auto text-left mb-4">Protect against legal liability</li>
		</ul>
		<div class="w-1/2 text-2xl mx-auto text-center mb-4">Security of Your Personal Data</div>
		<div class="w-3/4 mx-auto text-left mb-4">The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</div>
		<div class="w-1/2 text-2xl mx-auto text-center mb-4">Children's Privacy</div>
		<div class="w-3/4 mx-auto text-left mb-4">Our Service does not address anyone under the age of 14. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</div>
		<div class="w-3/4 mx-auto text-left mb-4">If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</div>
		<div class="w-1/2 text-2xl mx-auto text-center mb-4">Links to Other Websites</div>
		<div class="w-3/4 mx-auto text-left mb-4">Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</div>
		<div class="w-3/4 mx-auto text-left mb-4">We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</div>
		<div class="w-1/2 text-2xl mx-auto text-center mb-4">Changes to this Privacy Policy</div>
		<div class="w-3/4 mx-auto text-left mb-4">We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</div>
		<div class="w-3/4 mx-auto text-left mb-4">We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.</div>
		<div class="w-3/4 mx-auto text-left mb-4">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</div>
		<div class="w-1/2 text-2xl mx-auto text-center mb-4">Contact Us</div>
		<div class="w-3/4 mx-auto text-left pb-8">If you have any questions about this Privacy Policy, You can contact us: cjkbusiness96@gmail.com</div>
	</div>
</template>

<script>
export default {
	name: 'Follow-Bot-Privacy-Policy',
	head: {title: 'Privacy Policy'},
}
</script>

